# Generated by Django 3.0.6 on 2020-10-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnibusVelocidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True)),
                ('vel_trecho', models.IntegerField(null=True)),
                ('vel_via', models.IntegerField(null=True)),
                ('trecho', models.CharField(max_length=300, null=True)),
                ('extensao', models.IntegerField(null=True)),
                ('tempo', models.CharField(max_length=5, null=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnibusVelocidadeCoordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho', models.CharField(max_length=300, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('onibus_velocidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadas', to='onibus.OnibusVelocidade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OnibusPosicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_onibus', models.IntegerField()),
                ('onibus_deficiente', models.BooleanField()),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('horario_atualizacao_localizacao', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('frota', models.IntegerField()),
                ('id_linha', models.ForeignKey(db_column='id_linha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='linha.Linha', to_field='id_linha')),
            ],
        ),
        migrations.CreateModel(
            name='OnibusLotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_onibus', models.IntegerField()),
                ('lotacao', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('id_linha', models.ForeignKey(db_column='id_linha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='linha.Linha', to_field='id_linha')),
            ],
        ),
    ]
