# Generated by Django 3.0.6 on 2020-07-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Onibus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixo", models.IntegerField()),
                ("cod_linha", models.IntegerField()),
                ("lotacao", models.CharField(max_length=30)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=17)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=17)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
