# Generated by Django 3.0.6 on 2020-09-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onibusvelocidadecoordenadas',
            options={'ordering': ['id']},
        ),
    ]
