# Generated by Django 3.0.6 on 2020-07-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onibus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Onibus", new_name="OnibusLotacao",),
    ]
