# Generated by Django 3.0.6 on 2020-07-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linha", "0003_auto_20200729_2017"),
        ("onibus", "0002_auto_20200729_1954"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onibuslotacao", old_name="data", new_name="data_inclusao",
        ),
        migrations.RenameField(
            model_name="onibuslotacao", old_name="cod_linha", new_name="id_linha",
        ),
        migrations.RenameField(
            model_name="onibuslotacao", old_name="prefixo", new_name="id_onibus",
        ),
        migrations.CreateModel(
            name="OnibusPosicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_onibus", models.IntegerField()),
                ("onibus_deficiente", models.BooleanField()),
                ("data_inclusao", models.DateTimeField(auto_now_add=True)),
                ("horario_atualizacao_localizacao", models.CharField(max_length=30)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=17)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=17)),
                ("frota", models.IntegerField()),
                (
                    "id_linha",
                    models.ForeignKey(
                        db_column="id_linha",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="linha.Linha",
                        to_field="id_linha",
                    ),
                ),
            ],
        ),
    ]
