# Generated by Django 3.0.6 on 2020-09-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0002_auto_20200929_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onibusvelocidadecoordenadas',
            options={},
        ),
    ]
