# Generated by Django 3.0.6 on 2020-07-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linha', '0003_auto_20200729_2017'),
        ('onibus', '0003_auto_20200729_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onibuslotacao',
            name='id_linha',
            field=models.ForeignKey(db_column='id_linha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='linha.Linha', to_field='id_linha'),
        ),
    ]
