# Generated by Django 3.0.6 on 2020-08-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0005_auto_20200806_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onibuslotacao',
            name='lotacao',
            field=models.CharField(max_length=20),
        ),
    ]
