# Generated by Django 3.0.6 on 2020-08-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0006_auto_20200820_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='onibusposicao',
            name='sentido',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
