# Generated by Django 3.0.6 on 2020-09-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0008_remove_onibusposicao_sentido'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnibusVelocidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True)),
                ('vel_trecho', models.IntegerField(null=True)),
                ('vel_via', models.IntegerField(null=True)),
                ('trecho', models.CharField(max_length=300, null=True)),
                ('extensao', models.IntegerField(null=True)),
                ('tempo', models.CharField(max_length=5, null=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnibusVelocidadeCoordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho', models.CharField(max_length=300, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('onibus_velocidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadas', to='onibus.OnibusVelocidade')),
            ],
        ),
    ]
