# Generated by Django 3.0.6 on 2020-09-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0009_onibusvelocidade_onibusvelocidadecoordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onibusvelocidadecoordenadas',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='onibusvelocidadecoordenadas',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
