# Generated by Django 3.0.6 on 2020-09-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0010_auto_20200921_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onibusvelocidadecoordenadas',
            options={'ordering': ['trecho', 'latitude', 'longitude']},
        ),
    ]
