# Generated by Django 3.0.6 on 2020-08-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatempo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatempo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
