# Generated by Django 3.0.6 on 2020-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatempo', '0002_auto_20200810_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatempo',
            name='condicao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
