# Generated by Django 3.0.6 on 2020-07-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Chart",),
        migrations.DeleteModel(name="Dashboard",),
    ]
