# Generated by Django 3.0.6 on 2020-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linha', models.IntegerField(unique=True)),
                ('letreiro', models.CharField(max_length=80)),
                ('sentido', models.IntegerField()),
                ('letreiro_destino', models.CharField(max_length=80)),
                ('letreiro_origem', models.CharField(max_length=80)),
            ],
        ),
    ]
