# Generated by Django 3.0.6 on 2020-07-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Linha",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_linha", models.IntegerField()),
                ("letreiro", models.CharField(max_length=80)),
                ("sentido", models.IntegerField()),
                ("letreiro_destino", models.CharField(max_length=80)),
                ("letreiro_origem", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="OnibusCirculacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario_inclusao", models.DateTimeField(auto_now_add=True)),
                ("qtd_onibus", models.IntegerField()),
                (
                    "linha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="linha.Linha"
                    ),
                ),
            ],
        ),
    ]
