# Generated by Django 3.0.6 on 2020-07-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnibusCirculacao',
        ),
    ]
