# Generated by Django 3.0.6 on 2020-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linha', '0002_delete_onibuscirculacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='id_linha',
            field=models.IntegerField(unique=True),
        ),
    ]
