# Generated by Django 3.0.6 on 2020-09-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parada', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('endereco', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
            ],
        ),
    ]
