# Generated by Django 3.0.6 on 2020-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='nome',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
