# Generated by Django 3.0.6 on 2020-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
                ('data_info', models.CharField(max_length=500, null=True)),
                ('data', models.DateField(null=True)),
                ('endereco', models.CharField(max_length=700, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17, null=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
