# Generated by Django 3.0.6 on 2020-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
    ]
